config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, :controllers => { registrations: "users/registrations" }
  root "static_pages#home"
  resources :destinations
  resources :locations
  resources :events
  resources :users
  resources :posts
  resources :culturals

  namespace :admin do
    root "static_pages#home"
    resources :users
    resources :destinations
    resources :locations
    resources :events
    resources :posts
    resources :notification_events
    resources :join_events
    resources :culturals
    resources :categories
  end
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :culturals, dependent: :destroy
  has_many :suggests, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :ratings, as: :rateable, dependent: :destroy

  mount_uploader :image, PictureUploader

  validates :name, presence: true, length: {maximum: Settings.maximum_name}
  validates :description, presence: true, length: {minimum: Settings.minimum}
  validates :content, presence: true, length: {minimum: Settings.minimum}
  validates :place_id, uniqueness: true
  validate :image_size

  scope :newest, ->{order created_at: :desc}
  scope :name_asc, ->{order name: :asc}

  private

  def image_size
    if image.size > Settings.mb.megabytes
      errors.add :image, t("model.hinhanh")
    end
  end
end

app/controllers/admin/destinations_controller.rb
class Admin::DestinationsController < AdminController
  before_action :load_destination, except: [:index, :new, :create]

  def index
    @destinations = Destination.newest.page(params[:page]).
      per Settings.per_page
  end

  def new
    @destination = Destination.new
  end

  def create
    @destination = Destination.new destination_params
    if @destination.save
      flash[:success] = t "view.admin.destinations.themthanhcong"
      redirect_to admin_destinations_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @destination.update_attributes destination_params
      flash[:success] = t "view.admin.destinations.capnhapthanhcong"
      redirect_to admin_destinations_url
    else
      flash[:danger] = t "view.admin.destinations.capnhapthatbai"
      render :edit
    end
  end

  def destroy
    status_ok = true
    unless @destination.destroy
      status_ok = false
    end
    respond_to do |format|
      format.json {
        render json: {status_ok: status_ok}
      }
    end
  end

  private

  def destination_params
    params.require(:destination).permit :name, :image, :content, :description,
      :status, :place_id
  end

  def load_destination
    @destination = Destination.find_by id: params[:id]
    return if @destination
    flash[:warning] = t "view.admin.destinations.loi"
    redirect_to admin_destinations_url
  end
end

app/views/admin/destinations/_form.html.erb
<%= form_for [:admin, @destination],
  html: {multipart: true} do |destination| %>
  <%= render "shared/error_messages", object: destination.object %>
  <table class="table table-user-information">
    <tbody>
      <tr>
        <td>
          <%= destination.label t "view.admin.destinations.chontinhthanh" %>
          <br>
        </td>
        <td>
          <%= destination.hidden_field :place_id %>
          <div id="map" class="map"></div>
        </td>
      </tr>
      <tr>
        <td>
          <%= destination.label t "view.admin.destinations.ten" %>
        </td>
        <td><%= destination.text_field :name, class: "form-control",
          required: true %>
        </td>
      </tr>
      <tr>
        <td>
          <%= destination.label t "view.admin.destinations.hinhanh" %>
        </td>
        <td>
          <span class="picture">
            <%= destination.file_field :image,
              accept: Settings.accept_image %>
          </span>
        </td>
      </tr>
      <tr>
        <td>
          <%= destination.label t "view.admin.destinations.gioithieu" %>
          <br>
        </td>
        <td>
          <%= destination.text_area :description,
            class: "textarea-destination" %>
        </td>
      </tr>
      <tr>
        <td>
          <%= destination.label t "view.admin.destinations.noidung" %>
          <br>
        </td>
        <td>
          <%= destination.cktext_area :content,
            class: "textarea-destination" %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="submit-add-destination">
    <%= destination.submit yield(:button_text),
      class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/destinations/_list_destinations.html.erb
<tr id="del-destination-<%= destination.id %>">
  <td class="text-center"><strong><%= destination.id %></strong></td>
  <td class="text-center"><%= destination.name %></td>
  <td class="text-center">
    <div>
      <%= image_tag destination.image.url, class: "image_user"  %>
    </div>
  </td>
  <td class="text-center"><%= l destination.created_at, format: :short %></td>
  <td class="text-center">
    <div class="btn-group btn-group-xs">
      <button class="btn btn-default" data-toggle="modal"
        title= <%= t "view.admin.destinations.xem" %>
          data-target="#view-destination-<%= destination.id %>">
        <i class="fa fa-eye"></i>
      </button>
      <%= link_to edit_admin_destination_path(destination.id),
        class: "btn btn-default",
        title: t("view.admin.destinations.chinhsua") do %>
         <i class="fa fa-pencil"></i>
      <% end %>
      <a data-destinationid="<%= destination.id %>"
        title= <%= t "view.admin.destinations.xoa" %>
        class="btn btn-default del-destination" href="#" >
        <i class="fa fa-times"></i>
      </a>
    </div>
    <%= render partial: "view_destination",
      locals: {destination: destination} %>
  </td>
</tr>

app/views/admin/destinations/_view_destination.html.erb
<div class="modal fade" id="view-destination-<%= destination.id %>"
  tabindex="-1" role="dialog" aria-labelledby="Viewdestination"
  aria-hidden="true">
  <div class="modal-dialog modal-add-destination">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
          aria-hidden="true">&times;
        </button>
        <div class="modal-header text-center">
          <h2 class="modal-title"><i class="fa fa-th-list"></i>
            <%= t "view.admin.destinations.chitietbaiviet" %>
          </h2>
        </div>
      </div>
      <div class="modal-body">
        <table class="table table-user-information">
          <tbody>
            <tr>
              <td><%= t "view.admin.destinations.id" %></td>
              <td><%= destination.id %></td>
            </tr>
            <tr>
              <td><%= t "view.admin.destinations.ten" %></td>
              <td><%= destination.name %></td>
            </tr>
            <tr>
              <td><%= t "view.admin.destinations.thoigiandang" %></td>
              <td><%= l destination.created_at, format: :short %></td>
            </tr>
            <tr>
              <td><%= t "view.admin.destinations.luotxem" %></td>
              <td><%= destination.count_view %></td>
            </tr>
            <tr>
              <td><%= t "view.admin.destinations.hinhanh" %></td>
              <td>
                <%= image_tag destination.image.url, class: "image_user" %>
              </td>
            </tr>
            <tr>
              <td><%= t "view.admin.destinations.gioithieu" %></td>
              <td><%= destination.description %></td>
            </tr>
            <tr>
              <td><%= t "view.admin.destinations.noidung" %></td>
              <td><%= raw destination.content %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <%= t "thoat" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/admin/destinations/edit.html.erb
<% provide :button_text, t("view.admin.destinations.luuthaydoi") %>

<div class="modal-header text-center">
  <h2 class="modal-title"><i class="fa fa-th-list"></i>
    <%= t "view.admin.destinations.chinhsua" %>
  </h2>
</div>

<%= render "form" %>

<%= javascript_include_tag "google_map/map_choice_province" %>

app/views/admin/destinations/index.html.erb
<% provide :title, t("khamphavietnam") %>
<div class="content-header">
  <div class="header-section">
    <h1>
      <i class="gi gi-table"></i><%= t "view.admin.destinations.danhsach" %>
    </h1>
  </div>
</div>
<ul class="breadcrumb breadcrumb-top">
  <li><%= link_to t("trangchu"), admin_root_path %></li>
  <li><%= link_to t("khamphavietnam"), admin_destinations_path %></li>
</ul>
<div>
  <%= link_to new_admin_destination_path, class: "btn btn-primary btn-lg" do %>
    <i class="fa fa-th-list"> <%= t "view.admin.destinations.thembaiviet" %></i>
  <% end %>
</div>
<div class="block">
  <div class="block-title">
    <h2><strong><%= t "view.admin.destinations.danhsach" %></strong></h2>
  </div>
  <div class="table-responsive">
    <table id="general-table" class="table table-striped table-vcenter">
      <thead>
        <tr>
          <th class="text-center"><%= t "view.admin.destinations.id" %></th>
          <th class="text-center"><%= t "view.admin.destinations.ten" %></th>
          <th class="text-center">
            <%= t "view.admin.destinations.hinhanh" %>
          </th>
          <th class="text-center">
            <%= t "view.admin.destinations.ngaydang" %>
          </th>
          <th class="text-center">
            <%= t "view.admin.destinations.hanhdong" %>
          </th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "list_destinations",
          collection: @destinations, as: :destination %>
      </tbody>
    </table>
  </div>
</div>
<div id="page-categories" >
  <%= paginate @destinations %>
</div>

app/views/admin/destinations/new.html.erb
<% provide :button_text, t("view.admin.destinations.thembaiviet") %>

<div class="modal-header text-center">
  <h2 class="modal-title"><i class="fa fa-th-list"></i>
    <%= t "view.admin.destinations.thembaiviet" %>
  </h2>
</div>

<%= render "form" %>

<%= javascript_include_tag "google_map/map_choice_province" %>