config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, :controllers => { registrations: "users/registrations" }
  root "static_pages#home"
  resources :destinations
  resources :locations
  resources :events
  resources :users
  resources :posts
  resources :culturals

  namespace :admin do
    root "static_pages#home"
    resources :users
    resources :destinations
    resources :locations
    resources :events
    resources :posts
    resources :notification_events
    resources :join_events
    resources :culturals
    resources :categories
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :join_events, dependent: :destroy

  belongs_to :destination

  mount_uploader :image, PictureUploader

  validates :title, presence: true, length: {maximum: Settings.maximum_name}
  validates :content, presence: true, length: {minimum: Settings.minimum}
  validate :start_date_before_end_date
  validates :time_end, presence: true
  validates :time_start, presence: true
  validate :image_size

  delegate :name, to: :destination, prefix: true

  scope :newest, ->{order created_at: :desc}
  scope :allow_registration, ->do
    where "? BETWEEN time_start AND time_end", Time.now.to_date
  end
  scope :not_allow_registration, ->{where "? > time_end ", Time.now.to_date}

  private

  def start_date_before_end_date
    if self.time_start > self.time_end
      errors.add(:time_start, t("model.validate_time"))
    end
  end

  def image_size
    if image.size > Settings.mb.megabytes
      errors.add :image, t("model.hinhanh")
    end
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  before_action :load_event, except: [:index, :new, :create]
  before_action :load_destinations, only: [:new, :edit, :update]

  def index
    @events = Event.newest.page(params[:page]).per Settings.per_page
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new event_params
    if @event.save
      flash[:success] = t "view.admin.events.themthanhcong"
      redirect_to admin_events_url
    else
      render :new
    end
  end

  def update
    if @event.update_attributes event_params
      flash[:success] = t "view.admin.events.capnhapthanhcong"
      redirect_to admin_events_url
    else
      render :edit
    end
  end

  def destroy
    status_ok = true
    unless @event.destroy
      status_ok = false
    end
    respond_to do |format|
      format.json {
        render json: {status_ok: status_ok}
      }
    end
  end

  private

  def event_params
    params.require(:event).permit :title, :image, :content,
      :status, :time_start, :time_end, :destination_id
  end

  def load_event
    @event = Event.find_by id: params[:id]
    return if @event
    flash[:warning] = t "view.admin.events.loi"
    redirect_to admin_events_url
  end

  def load_destinations
    @destinations = Destination.all.name_asc
    return if @destinations.present?
    flash[:warning] = t "view.admin.events.loi_destination"
    redirect_to admin_events_url
  end
end

app/helpers/event_helper.rb
module EventHelper
  def check_status_event time_start, time_end
    if Time.now.to_date < time_start.to_date
      "<span class='label label-warning'>" <<
        t('view.admin.events.chuachophepdangky') << "</span>"
    elsif Time.now.to_date >= time_start.to_date &&
      Time.now.to_date <= time_end.to_date
      "<span class='label label-success'>" <<
        t("view.admin.events.chophepdangky") << "</span>"
    else
      "<span class='label label-danger'>" <<
        t("view.admin.events.daketthuc") << "</span>"
    end
  end
end

app/views/admin/events/_list_events.html.erb
<tr id="del-event-<%= event.id %>">
  <td class="text-center"><strong><%= event.id %></strong></td>
  <td class="text-center"><%= event.title %></td>
  <td class="text-center">
    <div>
      <%= image_tag event.image.url, class: "image_user"  %>
    </div>
  </td>
  <td class="text-center"><%= event.destination_name %></td>
  <td class="text-center"><%= event.time_start %> - <%= event.time_end %></td>
  <td class="text-center">
    <%= raw check_status_event event.time_start, event.time_end %>
  </td>
  <td class="text-center">
    <div class="btn-group btn-group-xs">
      <%= link_to admin_join_events_path(id: event.id),
        class: "btn btn-default",
        title: t("view.admin.events.thanhvien") do %>
        <i class="fa fa-user"></i>
      <% end %>
      <button class="btn btn-default" data-toggle="modal"
        title= <%= t "view.admin.events.xem" %>
        data-target="#view-event-<%= event.id %>">
        <i class="fa fa-eye"></i>
      </button>
      <%= link_to edit_admin_event_path(event.id),
        class: "btn btn-default",
        title: t("view.admin.events.chinhsua") do %>
        <i class="fa fa-pencil"></i>
      <% end %>
      <%= link_to "#", data: {eventid: event.id},
        title: t("view.admin.events.xoa"),
        class: "btn btn-default del-event" do %>
        <i class="fa fa-times"></i>
      <% end %>
    </div>
    <%= render partial: "view_event", locals: {event: event} %>
  </td>
</tr>

app/views/admin/events/_view_event.html.erb
<div class="modal fade" id="view-event-<%= event.id %>"
  tabindex="-1" role="dialog" aria-labelledby="Viewevent"
  aria-hidden="true">
  <div class="modal-dialog modal-add-destination">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
          aria-hidden="true">&times;
        </button>
        <div class="modal-header text-center">
          <h2 class="modal-title"><i class="fa fa-th-list"></i>
            <%= t "view.admin.events.chitietbaiviet" %>
          </h2>
        </div>
      </div>
      <div class="modal-body">
        <table class="table table-user-information">
          <tbody>
            <tr>
              <td><%= t "view.admin.events.id" %></td>
              <td><%= event.id %></td>
            </tr>
            <tr>
              <td><%= t "view.admin.events.ten" %></td>
              <td><%= event.title %></td>
            </tr>
            <tr>
            <td><%= t "view.admin.events.trangthai" %></td>
              <td>
                <%= raw check_status_event event.time_start, event.time_end %>
              </td>
            </tr>
            <tr>
              <td><%= t "view.admin.events.tinhthanhpho" %></td>
              <td><%= event.destination_name %></td>
            </tr>
            <tr>
              <td><%= t "view.admin.events.thoigianbatdau" %></td>
              <td><%= event.time_start %></td>
            </tr>
            <tr>
              <td><%= t "view.admin.events.thoigianketthuc" %></td>
              <td><%= event.time_end %></td>
            </tr>
            <tr>
              <td><%= t "view.admin.events.thoigiandang" %></td>
              <td><%= l event.created_at, format: :short %></td>
            </tr>
            <tr>
              <td><%= t "view.admin.events.hinhanh" %></td>
              <td>
                <%= image_tag event.image.url, class: "image_user" %>
              </td>
            </tr>
            <tr>
              <td><%= t "view.admin.events.noidung" %></td>
              <td><%= raw event.content %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <%= t "thoat" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/admin/events/edit.html.erb
<div class="modal-header text-center">
  <h2 class="modal-title"><i class="fa fa-th-list"></i>
    <%= t "view.admin.events.chinhsua" %>
  </h2>
</div>
<%= form_for [:admin, @event], html: {multipart: true} do |event| %>
  <%= render "shared/error_messages", object: event.object %>
  <table class="table table-user-information">
    <tbody>
      <tr>
        <td>
          <%= event.label t "view.admin.events.ten" %>
        </td>
        <td>
          <%= event.text_field :title, class: "form-control", required: true %>
        </td>
      </tr>
      <tr>
        <td><%= event.label t "view.admin.events.tinhthanhpho" %></td>
        <td><%= event.collection_select :destination_id,
          @destinations, :id, :name, {prompt: false}, {class: "form-control"} %>
        </td>
      </tr>
      <tr>
        <td><%= event.label t "view.admin.events.thoigianbatdau" %></td>
        <td>
          <%= event.text_field :time_start, data: {provide: "datepicker"},
            class: "datepicker" %>
        </td>
      </tr>
      <tr>
        <td><%= event.label t "view.admin.events.thoigianketthuc" %></td>
        <td>
          <%= event.text_field :time_end, data: {provide: "datepicker"},
            class: "datepicker" %>
        </td>
      </tr>
      <tr>
        <td><%= t "view.admin.events.old_image" %></td>
        <td>
          <%= image_tag event.object.image.url, class: "image_user" %>
        </td>
      </tr>
      <tr>
        <td>
          <%= event.label t "view.admin.events.hinhanh" %>
        </td>
        <td>
          <span class="picture">
            <%= event.file_field :image, accept: Settings.accept_image %>
          </span>
        </td>
      </tr>
      <tr>
        <td>
          <%= event.label t "view.admin.events.noidung" %>
          <br>
        </td>
        <td>
          <%= event.cktext_area :content, class: "textarea-event" %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="submit-add-destination">
    <%= event.submit t("view.admin.events.luuthaydoi"),
      class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/events/index.html.erb
<% provide :title, t("view.admin.events.sukien") %>
<div class="content-header">
  <div class="header-section">
    <h1>
      <i class="gi gi-table"></i><%= t "view.admin.events.danhsach" %>
    </h1>
  </div>
</div>
<ul class="breadcrumb breadcrumb-top">
  <li><%= link_to t("trangchu"), admin_root_path %></li>
  <li><%= t "view.admin.events.danhsach" %></li>
</ul>
<div>
  <%= link_to new_admin_event_path, class: "btn btn-primary btn-lg" do %>
    <i class="fa fa-th-list"> <%= t "view.admin.events.themsukien" %></i>
  <% end %>
</div>
<div class="block">
  <div class="block-title">
    <h2><strong><%= t "view.admin.events.danhsach" %></strong></h2>
  </div>
  <div class="table-responsive">
    <table id="general-table" class="table table-striped table-vcenter">
      <thead>
        <tr>
          <th class="text-center"><%= t "view.admin.events.id" %></th>
          <th class="text-center"><%= t "view.admin.events.tieude" %></th>
          <th class="text-center">
            <%= t "view.admin.events.hinhanh" %>
          </th>
          <th class="text-center">
            <%= t "view.admin.events.tinhthanhpho" %>
          </th>
          <th class="text-center">
            <%= t "view.admin.events.thoigiandangky" %>
          </th>
          <th class="text-center">
            <%= t "view.admin.events.trangthai" %>
          </th>
          <th class="text-center">
            <%= t "view.admin.events.hanhdong" %>
          </th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "list_events",
          collection: @events, as: :event %>
      </tbody>
    </table>
  </div>
</div>
<div class="submit-add-destination">
  <%= paginate @events %>
</div>

app/views/admin/events/new.html.erb
<div class="modal-header text-center">
  <h2 class="modal-title"><i class="fa fa-th-list"></i>
    <%= t "view.admin.events.themsukien" %>
  </h2>
</div>
<%= form_for [:admin, @event],
  html: {multipart: true} do |event| %>
  <%= render "shared/error_messages", object: event.object %>
  <table class="table table-user-information">
    <tbody>
      <tr>
        <td>
          <%= event.label t "view.admin.events.ten" %>
        </td>
        <td><%= event.text_field :title, class: "form-control",
          required: true %>
        </td>
      </tr>
      <tr>
        <td><%= event.label t "view.admin.events.tinhthanhpho" %></td>
        <td><%= event.collection_select :destination_id,
          @destinations, :id, :name, {prompt: false}, {class: "form-control"} %>
        </td>
      </tr>
      <tr>
        <td><%= event.label t "view.admin.events.thoigianbatdau" %></td>
        <td>
          <%= event.text_field :time_start, data: {provide: "datepicker"},
            class: "datepicker" %>
        </td>
      </tr>
      <tr>
        <td><%= event.label t "view.admin.events.thoigianketthuc" %></td>
        <td>
          <%= event.text_field :time_end, data: {provide: "datepicker"},
            class: "datepicker" %>
        </td>
      </tr>
      <tr>
        <td>
          <%= event.label t "view.admin.events.hinhanh" %>
        </td>
        <td>
          <span class="picture">
            <%= event.file_field :image,
              accept: Settings.accept_image %>
          </span>
        </td>
      </tr>
      <tr>
        <td>
          <%= event.label t "view.admin.events.noidung" %>
          <br>
        </td>
        <td>
          <%= event.cktext_area :content,
            class: "textarea-event" %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="submit-add-destination">
    <%= event.submit t("view.admin.events.themsukien"),
      class: "btn btn-primary" %>
  </div>
<% end %>