config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, :controllers => { registrations: "users/registrations" }
  root "static_pages#home"
  resources :destinations
  resources :locations
  resources :events
  resources :users
  resources :posts
  resources :culturals

  namespace :admin do
    root "static_pages#home"
    resources :users
    resources :destinations
    resources :locations
    resources :events
    resources :posts
    resources :notification_events
    resources :join_events
    resources :culturals
    resources :categories
  end
end

app/models/join_event.rb
class JoinEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event

  delegate :name, to: :user, prefix: true
  delegate :email, to: :user, prefix: true
  delegate :phone, to: :user, prefix: true
  delegate :address, to: :user, prefix: true

  scope :find_by_event, ->id {where event_id: id}
  scope :newest, ->{order created_at: :desc}
end

app/controllers/admin/join_events_controller.rb
class Admin::JoinEventsController < AdminController
  before_action :load_event, only: [:index, :create]
  before_action :load_join_event, only: :destroy

  def index
    @join_events = JoinEvent.find_by_event(@event.id).newest.
      page(params[:page]).per Settings.per_page
  end

  def destroy
    status_ok = true
    unless @join_event.destroy
      status_ok = false
    end
    respond_to do |format|
      format.json {
        render json: {status_ok: status_ok}
      }
    end
  end

  private

  def load_join_event
    @join_event = JoinEvent.find_by id: params[:id]
    return if @join_event
    flash[:warning] = t "view.admin.events.loi"
    redirect_to admin_join_events_url
  end

  def load_event
    @event = Event.find_by id: params[:id]
    return if @event
    flash[:warning] = t "view.admin.events.loi"
    redirect_to admin_join_events_url
  end
end

app/views/admin/join_events/_form_send_mail.html.erb
<div class="modal fade" id="send-mail-join-event" tabindex="-1" role="dialog"
  aria-labelledby="AddUser" aria-hidden="true">
  <div class="modal-dialog modal-add-destination">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
          aria-hidden="true">&times;
        </button>
        <div class="modal-header text-center">
          <h2 class="modal-title"><i class="hi hi-user"></i>
            <%= t "view.admin.join_events.thongbao" %>
          </h2>
        </div>
      </div>
      <div class="modal-body">
        <%= form_tag admin_notification_events_path(id: @event.id),
          html: {method: :post},
          class: "navbar-form", role: "search" do %>
          <div class="price-top">
            <h4><b><i><%= t "view.admin.join_events.tieude" %></i></b></h4>
          </div>
          <div>
            <%= text_field_tag :title, params[:title], class: "form-control",
              required: :true %>
          </div>
          <div class="price-top">
            <h4><b><i><%= t "view.admin.join_events.noidung" %></i></b></h4>
          </div>
          <div class="input-group add-on">
            <%= cktext_area_tag :content, params[:content],
              class: "form-control" %>
          </div>
          <div class="input-group-btn submit-add-destination">
            <%= submit_tag t("view.admin.join_events.guithu"),
              class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <%= t "thoat" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/admin/join_events/_list_join_events.html.erb
<tr class="active" id="del-join-event-<%= join_event.id %>">
  <td><%= join_event.user_name %></td>
  <td><%= join_event.user_email %></td>
  <td><%= join_event.user_phone %></td>
  <td><%= join_event.user_address %></td>
  <td class="text-center">
    <div class="btn-group btn-group-xs">
      <a data-join-eventid="<%= join_event.id %>"
        title= <%= t "view.admin.users.xoa" %>
        class="btn btn-default del-join-event" href="#" >
        <i class="fa fa-times"></i>
      </a>
    </div>
  </td>
</tr>

app/views/admin/join_events/index.html.erb
<% provide :title, t("view.admin.users.thanhvien") %>
<div class="content-header">
  <div class="header-section">
    <h1>
      <i class="gi gi-table"></i>
      <%= t "view.admin.join_events.danhsachthanhvien" %>
      <br>
    </h1>
  </div>
</div>
<ul class="breadcrumb breadcrumb-top">
  <li><%= link_to t("trangchu"), admin_root_path %></li>
  <li>
    <%= t "view.admin.join_events.danhsachthanhvien" %>
  </li>
</ul>
<div>
  <h3>
    <p>
      <b><%= t "view.admin.join_events.sukien" %>: </b>
      <%= @event.title %>
    </p>
    <p>
      <b><%= t "view.admin.join_events.sothanhvienthamgia" %>:</b>
      <%= @event.join_events.size %>
    </p>
    <p>
    <b><%= t "view.admin.join_events.thoigiandangky" %>: </b>
      <%= @event.time_start %> - <%= @event.time_end %>
    </p>
    <p>
      <b><%= t "view.admin.join_events.trangthai" %>:</b>
      <%= raw check_status_event @event.time_start, @event.time_end %>
    </p>
  </h3>
  </br></br>
</div>
<div>
  <button class="btn btn-primary btn-lg" data-toggle="modal"
    data-target="#send-mail-join-event">
    <i class="fa fa-join_event"> <%= t "view.admin.join_events.guithu" %></i>
  </button>
</div>
<div class="block">
  <div class="block-title">
    <h2>
      <strong><%= t "view.admin.join_events.danhsachthanhvien" %></strong>
    </h2>
  </div>
  <div class="table-responsive">
    <table id="general-table" class="table table-striped table-vcenter">
      <thead>
        <tr>
          <th><%= t "view.admin.users.hoten" %></th>
          <th><%= t "view.admin.users.email" %></th>
          <th><%= t "view.admin.users.sdt" %></th>
          <th><%= t "view.admin.users.diachi" %></th>
          <th class="text-center"><%= t "view.admin.users.hanhdong" %></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "list_join_events",
          collection: @join_events, as: :join_event %>
      </tbody>
    </table>
  </div>
</div>
<div class="submit-add-destination">
  <h4><%= paginate @join_events %></h4>
</div>
<%= render "form_send_mail" %>