config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :users, :controllers => { registrations: "users/registrations" }
  root "static_pages#home"
  resources :destinations
  resources :locations
  resources :events
  resources :users
  resources :posts
  resources :culturals

  namespace :admin do
    root "static_pages#home"
    resources :users
    resources :destinations
    resources :locations
    resources :events
    resources :posts
    resources :notification_events
    resources :join_events
    resources :culturals
    resources :categories
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arrived.rb
class Arrived < ApplicationRecord
  belongs_to :location
  belongs_to :user
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :bookmarkable, polymorphic: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/cultural.rb
class Cultural < ApplicationRecord
  belongs_to :user
  belongs_to :destination
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :culturals, dependent: :destroy
  has_many :suggests, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :ratings, as: :rateable, dependent: :destroy

  mount_uploader :image, PictureUploader

  validates :name, presence: true, length: {maximum: Settings.maximum_name}
  validates :description, presence: true, length: {minimum: Settings.minimum}
  validates :content, presence: true, length: {minimum: Settings.minimum}
  validates :place_id, uniqueness: true
  validate :image_size

  scope :newest, ->{order created_at: :desc}
  scope :name_asc, ->{order name: :asc}

  private

  def image_size
    if image.size > Settings.mb.megabytes
      errors.add :image, t("model.hinhanh")
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :join_events, dependent: :destroy

  belongs_to :destination

  mount_uploader :image, PictureUploader

  validates :title, presence: true, length: {maximum: Settings.maximum_name}
  validates :content, presence: true, length: {minimum: Settings.minimum}
  validate :start_date_before_end_date
  validates :time_end, presence: true
  validates :time_start, presence: true
  validate :image_size

  delegate :name, to: :destination, prefix: true

  scope :newest, ->{order created_at: :desc}
  scope :allow_registration, ->do
    where "? BETWEEN time_start AND time_end", Time.now.to_date
  end
  scope :not_allow_registration, ->{where "? > time_end ", Time.now.to_date}

  private

  def start_date_before_end_date
    if self.time_start > self.time_end
      errors.add(:time_start, t("model.validate_time"))
    end
  end

  def image_size
    if image.size > Settings.mb.megabytes
      errors.add :image, t("model.hinhanh")
    end
  end
end

app/models/join_event.rb
class JoinEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event

  delegate :name, to: :user, prefix: true
  delegate :email, to: :user, prefix: true
  delegate :phone, to: :user, prefix: true
  delegate :address, to: :user, prefix: true

  scope :find_by_event, ->id {where event_id: id}
  scope :newest, ->{order created_at: :desc}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  belongs_to :destination

  has_many :arriveds, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :ratings, as: :rateable, dependent: :destroy
  has_many :bookmarks, as: :bookmarkable, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :ratings, as: :rateable, dependent: :destroy
  has_many :bookmarks, as: :bookmarkable, dependent: :destroy
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :rateable, polymorphic: true
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  belongs_to :destination
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :validatable

  has_many :locations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :culturals, dependent: :destroy
  has_many :suggests, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :arriveds, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :join_events, dependent: :destroy

  mount_uploader :image, PictureUploader

  VALID_FULLNAME_REGEX = /[\w]+([\s]+[\w]+){1}+/
  validates :name, presence: true, length: {maximum: Settings.maximum_name},
    format: {with: VALID_FULLNAME_REGEX}
  validates :phone, presence: true, numericality: {only_integer: true},
    length: {in: Settings.min_range_phone..Settings.max_range_phone}
  validates :address, presence: true,
    length: {maximum: Settings.maximum_address}
  validate  :image_size

  scope :newest, ->{order created_at: :desc}

  private

  def image_size
    if image.size > Settings.mb.megabytes
      errors.add :image, t("model.hinhanh")
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title
    base_title = t "pick_and_go"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def display_slide
    if params[:controller] == "devise/sessions" ||
     params[:controller] == "users/registrations"
      return false
    else
      return true
    end
  end
end

app/helpers/event_helper.rb
module EventHelper
  def check_status_event time_start, time_end
    if Time.now.to_date < time_start.to_date
      "<span class='label label-warning'>" <<
        t('view.admin.events.chuachophepdangky') << "</span>"
    elsif Time.now.to_date >= time_start.to_date &&
      Time.now.to_date <= time_end.to_date
      "<span class='label label-success'>" <<
        t("view.admin.events.chophepdangky") << "</span>"
    else
      "<span class='label label-danger'>" <<
        t("view.admin.events.daketthuc") << "</span>"
    end
  end
end

app/views/admin/layouts/_footer.html.erb
<footer class="clearfix">
  <div class="pull-right">
    <%= t "designed_by" %> <i class="fa fa-heart text-danger"></i>
    <a href="https://www.facebook.com/lam.tran.73"
      target="_blank"> <%= t "tran_lam" %>
    </a>
  </div>
  <div class="pull-left">
    <span> </span> <%= t "copy" %>;
    <a href="http://recruit.framgia.vn/" target="_blank">
      <%= t "framgia" %>
    </a>
  </div>
</footer>

app/views/admin/layouts/_header.html.erb
<div id="main-container">
  <header class="navbar navbar-default">
    <form action="page_ready_search_results.html" method="post"
      class="navbar-form-custom" role="search">
      <div class="form-group">
        <input type="text" id="top-search" name="top-search"
          class="form-control">
      </div>
    </form>
  </header>
<div id="page-content">

app/views/admin/layouts/_menu.html.erb
<div id="sidebar-scroll">
  <div class="sidebar-content">
    <%= link_to admin_root_path, class: "sidebar-brand" do %>
      <i class="gi gi-flash"></i>
      <span class="sidebar-nav-mini-hide">
        <strong><%= t "framgia" %></strong>
      </span>
    <% end %>
    <div
    class="sidebar-section sidebar-user clearfix sidebar-nav-mini-hide">
      <div class="sidebar-user-avatar">
        <%= image_tag "avatar.png" %>
      </div>
      <div class="sidebar-user-name"><%= t "name" %></div>
      <div class="sidebar-user-links">
        <a href="#modal-user-settings" data-toggle="modal"
        class="enable-tooltip" data-placement="bottom" title="Settings">
        <i class="gi gi-cogwheel"></i></a>
        <%= link_to "#", method: "delete", title: t("logout") do %>
          <i class="gi gi-exit"></i>
        <% end %>
      </div>
    </div>
      <ul
      class="sidebar-section sidebar-themes clearfix sidebar-nav-mini-hide">
      </ul>
      <ul class="sidebar-nav">
        <li class="sidebar-header">
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="gi gi-charts sidebar-nav-icon"></i>
            <span class="sidebar-nav-mini-hide">
              <%= t "name" %>
            </span>
          <% end %>
        </li>
        <li>
          <p></p>
        </li>
        <li>
          <%= link_to admin_users_path do %>
            <i class="gi gi-certificate sidebar-nav-icon"></i>
            <span class="sidebar-nav-mini-hide">
              <%= t "view.admin.layouts.quanlythanhvien" %>
            </span>
          <% end %>
        </li>
        <li>
          <p></p>
        </li>
        <li>
          <%= link_to admin_destinations_path do %>
            <i class="gi gi-show_big_thumbnails sidebar-nav-icon"></i>
            <span class="sidebar-nav-mini-hide">
              <%= t "khamphavietnam" %>
            </span>
          <% end %>
        </li>
        <li>
          <p></p>
        </li>
        <li>
          <%= link_to admin_locations_path do %>
            <i class="gi gi-show_big_thumbnails sidebar-nav-icon"></i>
            <span class="sidebar-nav-mini-hide">
              <%= t "diadiemphuot" %>
            </span>
          <% end %>
        </li>
        <li>
          <p></p>
        </li>
        <li>
          <%= link_to admin_events_path do %>
            <i class="gi gi-shopping_cart sidebar-nav-icon"></i>
            <span class="sidebar-nav-mini-hide">
              <%= t "sukien" %>
            </span>
          <% end %>
        </li>
        <li>
          <p></p>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="gi gi-leaf sidebar-nav-icon"></i>
            <span
              class="sidebar-nav-mini-hide"><%= t "name" %>
            </span>
          <% end %>
        </li>
        <li>
          <p></p>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="gi gi-show_big_thumbnails sidebar-nav-icon"></i>
            <span
              class="sidebar-nav-mini-hide"><%= t "slide" %>
            </span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/admin/layouts/_setting.html.erb
<div id="modal-user-settings"
  class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h2 class="modal-title">
          <i class="fa fa-pencil"></i><%= t "setting" %>
        </h2>
      </div>
      <div class="modal-body">
        <%= form_for current_user, url: admin_user_path(current_user),
          html: {method: "patch"} do |f| %>
          <fieldset>
            <legend><%= t "vital_info" %></legend>
            <div class="form-group">
              <label class="col-md-4 control-label"><%= t "name" %></label>
              <div class="col-md-8">
                <p class="form-control-static">
                  <%= f.text_field :name, class: "form-control" %>
                </p>
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-4 control-label" for="user-settings-email">
                <%= t "email" %>
              </label>
              <div class="col-md-8">
                <p class="form-control-static">
                  <%= f.text_field :email, class: "form-control" %>
                </p>
              </div>
            </div>
          </fieldset>
          <fieldset>
            <legend><%= t "password_update" %></legend>
              <div class="form-group">
                <label class="col-md-4 control-label"
                  for="user-settings-password">
                  <%= t "new_password" %>
                </label>
                <div class="col-md-8">
                  <%= f.password_field :password, class: "form-control",
                    placeholder: t("password") %>
                </div>
              </div>
              <div class="form-group">
                <label class="col-md-4 control-label"
                  for="user-settings-repassword">
                  <%= t "confirm_new_password" %>
                </label>
                <div class="col-md-8">
                  <%= f.password_field :password_confirmation,
                    placeholder: t("confirmation"), class: "form-control" %>
                </div>
              </div>
              <div class="form-group" id= setting_custom>
                <%= f.submit t("save_change"), class: "btn btn-primary" %>
              </div>
          </fieldset>
          <div class="form-group form-actions">
            <div class="col-xs-12 text-right">
              <button type="button" class="btn btn-sm btn-default"
                data-dismiss="modal"><%= t "close" %></button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="col-md-3 footer-left">
      <h2><%= link_to(image_tag "home/logo5.png") %></h2>
      <p><%= t "view.layouts.info_footer" %></p>
    </div>
    <div class="col-md-9 footer-right">
      <div class="col-sm-6 newsleft">
        <h3></h3>
      </div>
      <div class="col-sm-6 newsright">
        <form>
          <input type="text" value="Email">
          <input type="submit" value="<%= t 'view.layouts.gui' %>">
        </form>
      </div>
      <div class="clearfix"></div>
      <div class="sign-grds">
        <div class="col-md-4 sign-gd">
          <h4><%= t "thongtin" %></h4>
          <ul>
            <li><a href="index.html"><%= t "trangchu" %></a></li>
            <li><a href="mens.html"><%= t "khamphavietnam" %></a></li>
            <li><a href="womens.html"><%= t "diadiemphuot" %></a></li>
            <li>
              <a href="electronics.html"><%= t "view.layouts.meophuot" %>
              </a>
            </li>
            <li><a href="codes.html"><%= t "view.layouts.kinhnghiem" %></a></li>
            <li><a href="contact.html"><%= t "view.layouts.lienhe" %></a></li>
          </ul>
        </div>
        <div class="col-md-4 sign-gd-two">
          <h4><%= t "view.layouts.thongtin_pick_and_go" %></h4>
          <ul>
            <li>
              <i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>
              <%= t "view.layouts.diachi" %>: <%= t "view.layouts.danang" %>,
              <span><%= t "view.layouts.vietnam" %></span>
            </li>
            <li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i>
              <%= t "view.layouts.email" %> : <a href="pickandgo@gmail.com">
              <%= t "view.layouts.pickandgo" %></a>
            </li>
            <li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>
              <%= t "view.layouts.sdt" %>
            </li>
          </ul>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
    <div class="clearfix"></div>
    <p class="copy-right"><%= t "view.layouts.copy" %>
    <a href="http://w3layouts.com/"><%= t "view.layouts.framgia" %></a></p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header-bot">
  <div class="container">
    <div class="col-md-3 header-left">
      <h1><%= link_to(image_tag "home/logo5.png", class: "image-logo") %></h1>
    </div>
    <div class="col-md-6 header-middle">
      <form>
        <div class="search">
          <input type="search" value="Search">
        </div>
        <div class="section_room">
          <select id="country" onchange="change_country(this.value)"
            class="frm-field required">
            <option value="null">
              <%= t "view.layouts.chon_muc_timkiem" %>
            </option>
            <option value="1">
              <%= t "view.layouts.chon_muc_timkiem" %>
            </option>
            <option value="2">
              <%= t "view.layouts.chon_muc_timkiem" %>
            </option>
          </select>
        </div>
        <div class="sear-sub">
          <input type="submit" value=" ">
        </div>
        <div class="clearfix"></div>
      </form>
    </div>
    <div class="col-md-3 header-right footer-bottom">
      <ul>
        <li><a href="#" class="use1" data-toggle="modal" data-target="#login">
          <span><%= t "view.layouts.dangnhap" %></span></a>
        </li>
        <li><a class="fb" href="#"></a></li>
        <li><a class="twi" href="#"></a></li>
        <li><a class="insta" href="#"></a></li>
      </ul>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="ban-top">
  <div class="container">
    <div class="top_nav_left">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
              aria-expanded="false">
            <span class="sr-only"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse menu--shylock"
            id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav menu__list">
              <li class="active menu__item menu__item--current">
                <%= link_to root_path, class: "menu__link" do %>
                  <%= t "trangchu" %><span class="sr-only"></span>
                <% end %>
              </li>
              <li class=" menu__item"><%= link_to t("diadiemphuot"),
               locations_path, class: "menu__link" %>
              </li>
              <li class=" menu__item"><%= link_to t("khamphavietnam"),
                destinations_path, class: "menu__link" %>
              </li>
              <li class=" menu__item"><%= link_to t("sukien"), events_path,
                class: "menu__link" %>
              </li>
              <li class="dropdown menu__item">
                <a href="#" class="dropdown-toggle menu__link"
                  data-toggle="dropdown" role="button" aria-haspopup="true"
                  aria-expanded="false"><%= t "bog" %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu multi-column columns-3">
                  <div class="row">
                    <div class="col-sm-6 multi-gd-img1 multi-gd-text ">
                      <%= link_to image_tag("home/anh5.jpg") %>
                    </div>
                    <div class="col-sm-3 multi-gd-img">
                      <ul class="multi-column-dropdown">
                        <li>
                          <a href="mens.html"><%= t "view.layouts.meophuot" %>
                          </a>
                        </li>
                        <li>
                          <a href="mens.html"><%= t "view.layouts.kinhnghiem" %>
                          </a>
                        </li>
                        <li>
                          <a href="mens.html"><%= t "view.layouts.meophuot" %>
                          </a>
                        </li>
                      </ul>
                    </div>
                    <div class="clearfix"></div>
                  </div>
                </ul>
              </li>
              <% if user_signed_in? %>
                <li class="dropdown menu__item">
                  <a href="#" class="dropdown-toggle menu__link"
                    data-toggle="dropdown" role="button" aria-haspopup="true"
                    aria-expanded="false"><%= current_user.name %>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu multi-column columns-3">
                    <div class="row">
                      <div class="col-sm-4 multi-gd-img1 multi-gd-text ">
                        <%= link_to image_tag(current_user.image) %>
                      </div>
                      <div class="col-sm-3 multi-gd-img">
                        <ul class="multi-column-dropdown">
                          <li>
                            <a href="mens.html">
                              <%= t "view.layouts.hoso" %>
                            </a>
                          </li>
                          <li>
                            <%= link_to t("view.devise.edit"),
                              edit_user_registration_path %>
                          </li>
                          <li>
                            <%= link_to(t("view.devise.logout"),
                              destroy_user_session_path, method: :delete) %>
                          </li>
                        </ul>
                      </div>
                      <div class="clearfix"></div>
                    </div>
                  </ul>
                </li>

              <% else %>
                <li class=" menu__item"><%= link_to t("view.devise.login"),
                 new_user_session_path, class: "menu__link" %>
                </li>
                <li class=" menu__item"><%= link_to t("view.devise.signup"),
                 new_user_registration_path, class: "menu__link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/_sign_login.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog"
  aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-info">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
          aria-label="Close"><span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body modal-spa">
        <div class="login-grids">
          <div class="login">
            <div class="login-bottom">
              <h3><%= t "view.layouts.dangky" %></h3>
              <form>
                <div class="sign-up">
                  <h4><%= t "view.layouts.email" %> :</h4>
                  <input type="text" value="">
                </div>
                <div class="sign-up">
                  <h4><%= t "view.layouts.matkhau" %> :</h4>
                  <input type="password" value="">
                </div>
                <div class="sign-up">
                  <h4><%= t "view.layouts.confirmmatkhau" %> :</h4>
                  <input type="password" value="">
                </div>
                <div class="sign-up">
                  <input type="submit" value="" >
                </div>
              </form>
            </div>
            <div class="login-right">
              <h3><%= t "view.layouts.dangnhap" %></h3>
              <form>
                <div class="sign-in">
                  <h4><%= t "view.layouts.email" %> :</h4>
                  <input type="text" value="">
                </div>
                <div class="sign-in">
                  <h4><%= t "view.layouts.matkhau" %> :</h4>
                  <input type="password" value="">
                </div>
                <div class="sign-in">
                  <input type="submit" value="" >
                </div>
              </form>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_slide.html.erb
<div class="banner-grid">
  <div id="visual">
    <div class="slide-visual">
      <ul class="slide-group">
        <li>
          <%= image_tag "home/slide1.jpg", class: "img-responsive-slide" %>
        </li>
        <li>
          <%= image_tag "home/slide2.jpg", class: "img-responsive-slide" %>
        </li>
        <li>
          <%= image_tag "home/slide3.jpg", class: "img-responsive-slide" %>
        </li>
      </ul>
      <div class="script-wrap">
        <ul class="script-group">
          <li>
            <div class="inner-script">
              <%= image_tag "home/slide1.jpg",
                class: "img-responsive-subslide" %>
            </div>
          </li>
          <li>
            <div class="inner-script">
              <%= image_tag "home/slide2.jpg",
                class: "img-responsive-subslide" %>
            </div>
          </li>
          <li>
            <div class="inner-script">
              <%= image_tag "home/slide3.jpg",
                class: "img-responsive-subslide" %>
            </div>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "admin" %>
    <%= javascript_include_tag "admin" %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>
  <body>
    <div id="page-wrapper">
      <div id="page-container"
        class="sidebar-partial sidebar-visible-lg  sidebar-no-animations">
        <div id="sidebar">
          <%= render "admin/layouts/menu" %>
          <%= render "admin/layouts/header" %>
          <% flash.each do |message_type, message| %>
            <div id="indent-flash" class="alert alert-<%= message_type %>">
              <%= message %>
            </div>
          <% end %>
          <%= yield %>
          <%= render "admin/layouts/footer" %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyDiyjZrWfeOm7ucvA1pNjGIkSU693Hc_Ko&callback=initMap", defer: true %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <br>
    <% if display_slide %>
      <%= render "layouts/slide" %>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= render "layouts/sign_login" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "the_form_contains" %>
      <%= pluralize object.errors.count, t("error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>